### ISSUE TITLE
Why? I do not  know

### ISSUE THREAD

**Issue by jinli131419-David** [OpenBB-finance/OpenBB#7188]
FOMC Document Viewer (economy_fomc_documents_federal_reserve_obb):

[params]: Endpoint param with { roles: ["fileSelector"] } required for multi_file_viewer.

what is wrong?  help me

**Comment by deeleeramone** [comment]
Hi there, this was a breaking change introduced upstream and has been resolved with a new version.

You can update everything from the command line:

```
pip install -U "openbb[all]" --force-reinstall
```

Or you can update the affected packages only:

```
pip install -U openbb-platform-api openbb-federal-reserve
```

Start the server again and go back to the Apps page, and it should reload now.

**Comment by oghenekobirou** [comment]
> Hi there, this was a breaking change introduced upstream and has been resolved with a new version.
> 
> You can update everything from the command line:
> 
> ```
> pip install -U "openbb[all]" --force-reinstall
> ```
> 
> Or you can update the affected packages only:
> 
> ```
> pip install -U openbb-platform-api openbb-federal-reserve
> ```
> 
> Start the server again and go back to the Apps page, and it should reload now.

**Comment by MacLeeee** [comment]
still don't work. 
INFO:     127.0.0.1:53477 - "GET /widgets.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:53477 - "GET /apps.json HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:53477 - "GET /templates.json HTTP/1.1" 200 OK

**Comment by deeleeramone** [comment]
> still don't work. INFO: 127.0.0.1:53477 - "GET /widgets.json HTTP/1.1" 200 OK INFO: 127.0.0.1:53477 - "GET /apps.json HTTP/1.1" 404 Not Found INFO: 127.0.0.1:53477 - "GET /templates.json HTTP/1.1" 200 OK

Update all the openbb packages you have installed. Or, erase your environment and build it again.

**Comment by wa1king** [comment]
same. plz tick me if someone find the way to make it work

**Comment by sassanix** [comment]
This error is still there even with the update.

**Comment by rkefi** [comment]
Anyone found a solution? getting the same issue on fresh setup

**Comment by ChaNg1o1** [comment]
Still not working

**Comment by DidierRLopes** [comment]
Hey,

@wa1king @sassanix @rkefi @ChaNg1o1 - just spoke with @deeleeramone and this should have been fixed a long time ago.

have you tried to run "pip install -U "openbb[all]" --force-reinstall" ?

Pls let me know if this isn't fixed with it and share screenshot with the error so we can fixy.

**Comment by deeleeramone** [comment]
This was resolved in https://github.com/OpenBB-finance/OpenBB/releases/tag/4.4.4
